<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0b03cb7a-ee71-4b47-9def-1b8c538d0195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userLayout']/div[3]/div/div/div[3]/div/div[2]/div/ul/li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/svgs/Reader-Player - Download.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLayout&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;style_main__klHyQ&quot;]/div[@class=&quot;style_guideContainer__5Cg_w row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;fullscreen&quot;]/div[@class=&quot;ebookReader_ebookContainer__UzX5Y row&quot;]/div[@class=&quot;col-md-12&quot;]/ul[@class=&quot;ebookReader_controlBar__o3J4p&quot;]/li[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userLayout']/div[3]/div/div/div[3]/div/div[2]/div/ul/li/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/svgs/Reader-Player - Download.svg']</value>
   </webElementXpaths>
</WebElementEntity>
