<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome Sairam_Slider_arrowImg__KXFWs</name>
   <tag></tag>
   <elementGuidId>fe50412f-9549-4a08-b080-8a179008e2a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userLayout']/div[3]/div/div/section/div/div/div/div/button[2]/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fsvgs%2FRightArrowBlack.svg&amp;w=48&amp;q=75</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Slider_arrowImg__KXFWs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fsvgs%2FRightArrowBlack.svg&amp;w=32&amp;q=75 1x, /_next/image?url=%2Fsvgs%2FRightArrowBlack.svg&amp;w=48&amp;q=75 2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLayout&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;style_main__klHyQ&quot;]/div[@class=&quot;w-100 style_root__clq4x style_marginLeft__yCOME&quot;]/section[1]/div[@class=&quot;style_root__26ume&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;position-relative pt-4&quot;]/div[@class=&quot;Slider_carouselButtonGroup__v6aIv&quot;]/button[@class=&quot;styles_tertiary-round__dd9Ha Slider_carouselbutton__4FdKg&quot;]/span[1]/img[@class=&quot;Slider_arrowImg__KXFWs&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userLayout']/div[3]/div/div/section/div/div/div/div/button[2]/span/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=%2Fsvgs%2FRightArrowBlack.svg&amp;w=48&amp;q=75']</value>
   </webElementXpaths>
</WebElementEntity>
